multiformats/rust-multiaddr

- Cargo.toml
- src/protocol.rs
- tests/lib.rs
Looks like UTP and UDT codes were swapped when writing `protocols.rs`
> Fix typo in UTP/UDT protocol codes.

- Cargo.toml
- src/lib.rs
- src/parser.rs
- src/protocol.rs
> Replace varmint with integer-encoding

- src/lib.rs
This allows, for example, `Multiaddr`s to be used in a `HashMap`/`HashSet`.
> Trivially implement Hash

- .github/dependabot.yml
See https://dependabot.com/ for details on dependabot.
Part of the larger effort to switch rust-libp2p to upstream rust-multiaddr (https://github.com/libp2p/rust-libp2p/issues/758).
> .github: Add dependabot

- CHANGELOG.md
I would like to cut a new release of the `multiaddr` crate. Any objections? Anything that is not yet in `master` that you would like to see included?
> CHANGELOG: Prepare v0.12.0 release

- CHANGELOG.md
I would like to cut `multiaddr` crate `v0.13.0`. Among others, this will unblock https://github.com/libp2p/rust-libp2p/pull/2082 and thus pave the way for a new `libp2p` crate release.
Any objections? Anything you would like to see included before the release?
> CHANGELOG: Prepare v0.13.0 release

- CHANGELOG.md
- Cargo.toml
- src/protocol.rs
- tests/lib.rs
Hi @mxinden,
Creating this PR to close the issue #47.
This PR refers the Go code from [PR 153](https://github.com/multiformats/go-multiaddr/pull/153).
i have a couple of questions regarding the tests, it seems like we are missing a few tests:
1. [`construct_success`](https://github.com/multiformats/go-multiaddr/blob/eef92462702954520ff59a5bab357babd1a55ce5/multiaddr_test.go#L170-L173)
2. [`TestTextMarshaler`](https://github.com/multiformats/go-multiaddr/blob/eef92462702954520ff59a5bab357babd1a55ce5/multiaddr_test.go#L654-L668)
> Add support for `tls` protocol

- CHANGELOG.md
- Cargo.toml
> *: Bump version to v0.15.0 and add changelog entries

- CHANGELOG.md
- src/protocol.rs
- tests/lib.rs
https://github.com/multiformats/multiaddr/pull/131
> add `/webrtc` and `/certhash`

- CHANGELOG.md
This will allow the Rust WebRTC implementation to move forward. See https://github.com/libp2p/rust-libp2p/pull/2622#discussion_r995583142. //CC @melekes and @thomaseizinger
@dignifiedquire as the official ["Captain"](https://github.com/multiformats/rust-multiaddr#maintainers) of the project, any objections?
> CHANGELOG.md: Prepare v0.15.0

- .gitignore
- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/protocol.rs
- tests/lib.rs
A convenience for cases where _which_ protocols is of concern but the specific addresses are not, for example https://github.com/libp2p/rust-libp2p/issues/2758
> src/lib: Add Multiaddr::protocol_stack

- CHANGELOG.md
- README.md
- src/protocol.rs
- tests/lib.rs
Add `QuicV1` codepoint to represent QUIC Version 1 / RFC 9000. See https://github.com/multiformats/multiaddr/issues/145 for motivation. 
To be merged after https://github.com/multiformats/multicodec/pull/298.
> *: Add quic-v1 codepoint

- CHANGELOG.md
Unlocks https://github.com/libp2p/rust-libp2p/pull/2982.
Any objections by anyone? Anything else you would like to see included?
> CHANGELOG: Prepare v0.16.0

- CHANGELOG.md
- Cargo.toml
- src/protocol.rs
- tests/lib.rs
> src/protocol.rs: Add /webtransport

- Cargo.toml
- tests/lib.rs
- update crate to edition 2021
- update `multihash` to v0.18.0
- update `quickcheck` to v1.0.3
close #41 
close #49
> update crate to edition 2021

- Cargo.toml
- tests/lib.rs
and implement `Arbitrary` for `Multihash`.
Should be reviewed after #72 gets merged.
> Add missing versions to Proto arbitrary implementation

- .github/workflows/build.yml
- src/errors.rs
- src/protocol.rs
- tests/lib.rs
This PR follows both @mxinden and @thomaseizinger on #65. 
Tried to add multiple toolchains in a single step [but apparently it's not possible](https://github.com/actions-rs/toolchain/issues/215).
Test running [here](https://github.com/multiformats/rust-multiaddr/actions/runs/3743596561/jobs/6355945270#step:10:69)
Closes #65
> tests: add nightly test for Protocol Arbitrary impl to assert it covers all the Protocol variants.

- CHANGELOG.md
- Cargo.toml
- src/protocol.rs
- tests/lib.rs
With these features activated, `multihash` is quite heavy. Whilst we are in the process of fixing this, removing these features is a first good step towards that.
I think technically, this is a breaking change unfortunately because we re-export all of `multihash` and thus someone could have relied on the presence of `multihash::Code` through the re-export of `multihash`.
> fix: don't depend on unnecessary `multihash` features

- CHANGELOG.md
- src/protocol.rs
As an effort towards #71, mark `Protocol` as `non_exhaustive`. This allows us to add new variants without breaking downstream code.
I think matching on the `Protocol` is important, thus I chose to use `non_exhaustive` here over making it opaque.
> feat!: mark `Protocol` as `non_exhaustive`

- CHANGELOG.md
- Cargo.toml
- src/protocol.rs
- tests/lib.rs
Considered non-breaking change as `/webrtc` will still be parsed to `Protocol::WebRTC` and no known production deployment of `libp2p-webrtc` known.
See https://github.com/multiformats/multiaddr/pull/150#issuecomment-1468791586 for context.
@melekes @thomaseizinger can you take a look?
> fix: Rename `Protocol::WebRTC` string rep `/webrtc` to `/webrtc-direct`

- CHANGELOG.md
- src/protocol.rs
- tests/lib.rs
See https://github.com/multiformats/multiaddr/pull/150#issuecomment-1468791586 for context.
@melekes @thomaseizinger can you give this a review?
> fix: Rename `Protocol::WebRTC` to `Protocol::WebRTCDirect`

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/protocol.rs
- tests/lib.rs
With the latest releases of `multihash` and `libp2p-identity`, we can now make the `/p2p` protocol of `Multiaddr` type-safe.
Resolves #73.
Resolves #91.
> feat!: make `/p2p` type-safe

- CHANGELOG.md
- src/lib.rs
- tests/lib.rs
In order to have a uniformized usage of `multiaddr` with a `/p2p` suffix in the `rust-libp2p` repository, we are finding ourselves in need of utility method to easily ensure that a `multiaddr` is terminated by the `p2p` protocol for a given `PeerId`.
Our first thought was to only implement this method in our code base but since it is needed in several crates of ours and it could be useful to other people, we thought it could be a good idea to implement it directly on `Multiaddr`.
This is related to the following PR on the `rust-libp2p` repository: https://github.com/libp2p/rust-libp2p/pull/4596
After some discussions, we (@thomaseizinger and myself) decided to implement a simple `with_p2p` function on `multiaddr`.
We studied a possibility to improve the `push` and `with` functions to be …
> feat: add with_p2p method on multiaddr

- Cargo.toml
In Rust 1.80 cfg checking was introduced in stable. Since we use `cfg(nightly)` in one test to check the number of variants, we need to tell the compiler that this is okay.
It might seem like a dirty fix, but it's a widely used workaround:
- [`cfg(nightly)` exception in Cargo.toml](https://github.com/search?q=cfg%28nightly%29+lang%3Atoml&type=code)
- [`cfg(nightly)` in Rust files](https://github.com/search?q=cfg%28nightly%29+lang%3Arust+&type=code)
It's also one of the suggested solutions by rust itself (and it's more efficient then using a build.rs file).
_Originally posted by @umgefahren in https://github.com/multiformats/rust-multiaddr/issues/110#issuecomment-2265472969_
> chore: Add lint exception to make CI pass again

- src/protocol.rs
- tests/lib.rs
This PR implements all protocols listed in https://github.com/multiformats/multiaddr/blob/master/protocols.csv.
Presumably, this PR closes #97.
> Implement missing protocols

- Cargo.toml
- src/lib.rs
I aligned with rust-libp2p in that feature guarded items are now so documented.
> chore: Add doc auto cfg to show features in the documentation

- Cargo.toml
- src/lib.rs
Due to inner mutation `Bytes` had to be used instead of `Arc<[u8]>`, which achieves the same result as before, but without double indirection that was used before. Public API is unchanged.
`BytesMut::from(Bytes)` attempts to reuse allocation just like `Arc::make_mut()` did before.
Fixes https://github.com/multiformats/rust-multiaddr/issues/117
> Use `Bytes` to avoid double indirection with `Arc<Vec<u8>>`

- src/protocol.rs
- tests/lib.rs
Because my last PR took so long until it was merged, I overlooked that the `http-path` protocol had been standardized in the meantime.
This PR adds this protocol and thus creates feature parity with the Go implementation.
> Implement http-path protocol
